# Generated by Django 4.2.2 on 2023-07-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='formato',
            field=models.CharField(choices=[('txt', 'Texto'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], default='txt', max_length=10),
        ),
    ]
