# Generated by Django 4.2.2 on 2023-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documento_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
