# Generated by Django 4.2.2 on 2023-07-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documento_entregado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
