# Generated by Django 4.2.2 on 2023-07-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='intervalo',
            field=models.IntegerField(default=1),
        ),
    ]
